name: internalsystem
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  mobx: ^2.0.7
  provider: 6.1.2
  flutter_mobx: ^2.0.7
  material_design_icons_flutter: 7.0.7296
  http: ^1.2.1
  universal_html: ^2.2.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  mobx_codegen: ^2.0.7
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/background_login.png
    - assets/images/logo.png
  
  uses-material-design: true
